# Generated by Django 3.2.3 on 2021-05-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.BigIntegerField()),
                ('name', models.CharField(max_length=34)),
                ('subject', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('pwd', models.CharField(max_length=10)),
                ('regdate', models.DateTimeField()),
                ('hit', models.BigIntegerField()),
            ],
        ),
    ]
